name: Sync Fork

on:
  workflow_dispatch:
  #schedule:
  #- cron: "55 8-18 * * 1-5"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v3
        with:
          repository: 'maxafu/cryptum-api-connector'
          ref: 'master'
          token: '${{ secrets.PAT }}'
          path: 'maxafu'
          
      - uses: actions/checkout@v3
        with:
          repository: 'blockforce-official/cryptum-api-connector'
          ref: 'master'
          path: 'blockforce'
          
      - name: git-bash
        run: |    
          cd '/home/runner/work/cryptum-api-connector/cryptum-api-connector/maxafu'
          rm -R '!(*.git)'
          ls
          rsync -av --progress $GITHUB_WORKSPACE/blockforce-official/cryptum-api-connector /$GITHUB_WORKSPACE/maxafu/cryptum-api-connector --exclude '.git'
          
        
