name: Sync Fork

on:
  workflow_dispatch:
  #schedule:
  #- cron: "55 8-18 * * 1-5"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v3
        with:
          repository: 'maxafu/cryptum-api-connector'
          ref: 'master'
          token: '${{ github.PAT }}'
          path: 'maxafu'
          
      - uses: actions/checkout@v3
        with:
          repository: 'blockforce-official/cryptum-api-connector'
          ref: 'master'
          path: 'blockforce'
          
      - name: remote-bash
        # You may pin to the exact commit or the version.
        # uses: shinhwagk/remote-bash@c03b11eac4cceccef56a495916311d9d49875f4d
        uses: shinhwagk/remote-bash@0.0.1    
          cd '$GITHUB_WORKSPACE/maxafu/cryptum-api-connector'
          rm -R !(.git)
          ls
          rsync -av --progress $GITHUB_WORKSPACE/blockforce-official/cryptum-api-connector /$GITHUB_WORKSPACE/maxafu/cryptum-api-connector --exclude '.git'
          
        
